server:
  port: 6004
spring:
  application:
    name: service-video
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
# 阿里云视频上传key配置
aliyun:
  vod:
    file:
      keyid:
      keysecret:
      regionId:
